// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Suppress missing type declarations for dotenv in this environment
// @ts-ignore
import * as dotenv from "dotenv";
dotenv.config();
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL for migrations (port 5432) to avoid pgbouncer DDL issues;
    // fall back to DATABASE_URL for runtime queries (pgbouncer pooler).
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
